- name: Add cron job for galaxy
  cron:
    name: "galaxy_pg_cleanup"    
    user: galaxy
    weekday: "{{ galaxy_pg_cleanup_cron_weekday }}"
    hour: "{{ galaxy_pg_cleanup_cron_hour }}"
    minute: "00"
    job: gxadmin galaxy cleanup 10
